Repository AY2324S2-CS2103T-F11-4/tp, pull requests merged in 2024-04, with the labels that each got.

#113 Add no duplicate prefix check for birthday and dormtag
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: bug, priority.High

#118 Update User Guide & Icon
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/images/address_book_32.png
  src/main/resources/images/birthday_cake.png
  src/main/resources/images/calendar_alert.png
  src/main/resources/view/DarkTheme.css
Labels: documentation

#119 Update UG command summary
  docs/UserGuide.md
Labels: documentation

#116 Update fields to be dynamic
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Bug, severity.Low

#126 Update features for UG
  docs/UserGuide.md
Labels: documentation

#130 Free time interval check
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/FreeTimeTag.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTimeTag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/FreeTimeTagTest.java
Labels: priority.Medium

#137 Update UG contact fields
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#140 Add glossary to UG
  docs/UserGuide.md
Labels: documentation

#225 Fix bugs in UG
  docs/UserGuide.md
  docs/index.md
Labels: documentation, UG

#236 UML Revamp
  docs/diagrams/Dormie.puml
Labels: documentation
