Repository AY2324S2-CS2103T-F11-4/tp, pull requests merged in 2024-03, with the labels that each got.

#53 Add telegram criteria
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: enhancement, priority.Medium

#58 Change the build jar file name
  build.gradle
Labels: type.Enhancement

#69 Add class diagram for freeTime
  docs/diagrams/Dormie.puml
Labels: documentation

#78 Add free time tag
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/FreeTimeTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTimeTag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#80 Fix UG, site icon, site badges
  docs/UserGuide.md
  docs/images/dormie.png
  docs/index.md
  docs/site.json
Labels: documentation

#84 Update DG and message usage
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: documentation

#90 Enable assertion
  build.gradle
Labels: priority.High

#82 Fix birthday bug
  src/main/java/seedu/address/model/person/Birthday.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
Labels: type.Bug

#96 Add multi editing
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Enhancement

#107 Fix json dorm tag bug
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: bug, priority.High
